### PR TITLE
distance_bellman.cpp

### PR DESCRIPTION
**Pull request by amitkumarj441**
Implemented shortest path using Bellman-Ford Algorithm.

### CODE REVIEW

**Comment by acgetchell** [comment]
Hi Amit,

Thanks for the contribution. However, I cannot accept this commit without working tests and documentation. Also, it should be in a header file for inclusion into the main body of the program, as with the other items.

Thanks for your interest! I'll leave this open for now.

**Comment by amitkumarj441** [comment]
Hi @acgetchell ,

Thanks for letting me know about this. Please let me know how to test it. I'll soon document this code.

Cheers,
Amit Kumar Jaiswal

**Comment by acgetchell** [comment]
Hi @amitkumarj441,

I use GoogleTest. You can see working examples in the unittests directory.

Each header file will have associated tests. If the name of your file is BellmanFord.h in src, the test file will be BellmanFordTests.cpp in unittests.

Best,
Adam

**Comment by acgetchell** [comment]
Hi @amitkumarj441,

I haven't heard from you in over a month, and there's another commit that starts the ShortestPath algorithm, so I'm going to close this pull request. Please do build upon the current work in master, thank you!

**Comment by amitkumarj441** [comment]
Hi @acgetchell ,

Thanks for letting me know about this! Actually, I'm doing my internship from last month and that's why I unable to complete this PR, so please let me know where to start contributing to CDT-plusplus, i mean pending work!

Thank you
Amit Kumar Jaiswal

**Pull request closed without merging**
